### ISSUE TITLE
Compatibility with case sensitive file systems

### ISSUE THREAD

**Issue by matteopessina** [Zt-freak/DevOpsWorkItemRESTRequestButton#118]
Hi, 
I tried to build the project in linux, which has a case sensitive file system, and I got 
```ERROR in ./src/Components/RESTRequestButton/RESTRequestButton.tsx
Module not found: Error: Can't resolve './RestRequestButton.scss' in '/home/<OMITTED>/source/repos/Matteo/DevOpsWorkItemRESTRequestButton/src/Components/RESTRequestButton'
```
I find out that the issue is caused by the following line which reference the .scss file with a name that has a different case: `Rest` instead of `REST`.

https://github.com/Zt-freak/DevOpsWorkItemRESTRequestButton/blob/a29af3f835fcf1c8a2a21afb1444b671d2726c0d/src/Components/RESTRequestButton/RESTRequestButton.tsx#L5

**Comment by Zt-freak** [comment]
should be fixed now.
