### ISSUE TITLE
Let us choose the auth type

### ISSUE THREAD

**Issue by michvllni** [Zt-freak/DevOpsWorkItemRESTRequestButton#98]
As written in the title, It is required for me to use not bearer authentication but SAS authentication (which is directly in the URL, not in a header)

I'm getting 
![image](https://github.com/Zt-freak/DevOpsWorkItemRESTRequestButton/assets/45660891/0e2bbca2-d88e-4986-81a6-fe12cb5bb986)
when trying to use the button because it always sends a bearer token:
![image](https://github.com/Zt-freak/DevOpsWorkItemRESTRequestButton/assets/45660891/d20af377-7fa9-4877-92ee-e597dd9a49f5)

Would it be possible to add that?

**Comment by Zt-freak** [comment]
I'll add it

**Comment by Zt-freak** [comment]
There is a new configuration field which is for setting the default bearer token. by default it is true (to not break backwards compatibility), so you'll have to manually set it to false.

**Comment by Zt-freak** [comment]
![image](https://github.com/Zt-freak/DevOpsWorkItemRESTRequestButton/assets/26248881/0ac047a0-1bf8-4ee6-874f-2402fb13e572)

**Comment by Zt-freak** [comment]
sorry for the inconvenience, there have been some bugs
